## 공통 default 설정 부분, active에 따라 local or prod 실행
##정적 리소스 자동 갱신 false
spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  profiles:
    active: local
    include: oauth # oauth 설정 값 사용 하는 방법
  application:
    name: 3vs500

  ##java.lang.IllegalStateException: Failed to load ApplicationContext 에러 해결
  main:
    allow-bean-definition-overriding: true
  mustache:
    prefix: classpath:/templates/
    suffix: .mustache
  #Activemq 설정
  activemq:
    broker-url: ssl://b-510cbe43-6410-48ee-b743-d5d62c774e70-1.mq.ap-northeast-2.amazonaws.com:61617
    user: ApAdmin
    password: elwlxkf12#$56

  jpa:
    show-sql: false

## graphQL gui
graphql:
  spqr:
    gui:
      enabled: true
