spring:
  profiles: prod
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://###/AppleHipProd
      username: ###
      password: ###
      driver-class-name: org.mariadb.jdbc.Driver


chat:
  queue:
    size: "5"
    prefix: AP_CHAT

