## 공통 default 설정 부분, active에 따라 local or prod 실행
##정적 리소스 자동 갱신 false
spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  profiles:
    active: local
  application:
    name: 3vs500

  #Activemq 설정
  activemq:
    broker-url: ##
    user: ##
    password: ##

  jpa:
    show-sql: false

## graphQL gui
graphql:
  spqr:
    gui:
      enabled: true
