spring:
  profiles: prod
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://###/AppleHipDev
      username: ###
      password: ###
      driver-class-name: org.mariadb.jdbc.Driver

  chat:
    queue:
      size: "5"
      prefix: AP_CHAT