## 공통 default 설정 부분, active에 따라 local or prod 실행
##정적 리소스 자동 갱신 false
spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  profiles:
    active: local
    include: oauth # oauth 설정 값 사용 하는 방법
  application:
    name: 3vs500

  ##java.lang.IllegalStateException: Failed to load ApplicationContext 에러 해결
  main:
    allow-bean-definition-overriding: true

 #Activemq 설정
  activemq:
    broker-url: ##
    user: ##
    password: ##

  jpa:
    show-sql: false

## graphQL gui
graphql:
  spqr:
    gui:
      enabled: true
